
version: '3'

services:
  app:
    build: /server 
    entrypoint: .docker/entrypoint.sh 
    container_name: hubla-app 
    ports:
      - "3000:3000" 
      - "5555:5555"
      - "8000:8000"
    volumes:
      - .:/home/node/app 
    depends_on:
      - db 
    environment:
      - DATABASE_URL=postgresql://postgres:docker@db:5432/hubla?schema=public
      - NODE_ENV=development
      - PORT=3000

  db:
    build: .docker/postgres 
    container_name: hubla-db
    restart: always 
    tty: true 
    ports:
      - "5432:5432"
    volumes:
      - /.docker/dbdata:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=docker 
      - POSTGRES_DB=hubla 

